// // This file was generated by SquareLine Studio
// // SquareLine Studio version: SquareLine Studio 1.5.3
// // LVGL version: 8.3.6
// // Project name: esp32_rc

// #include "../ui.h"

// lv_obj_t * uic_DataScreen;
// lv_obj_t * ui_DataScreen = NULL;
// lv_obj_t * ui_TextArea3 = NULL;
// lv_obj_t * ui_TextArea4 = NULL;
// // event funtions

// // build funtions

// void ui_DataScreen_screen_init(void)
// {
//     ui_DataScreen = lv_obj_create(NULL);
//     lv_obj_clear_flag(ui_DataScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_TextArea3 = lv_textarea_create(ui_DataScreen);
//     lv_obj_set_width(ui_TextArea3, 60);
//     lv_obj_set_height(ui_TextArea3, 37);
//     lv_obj_set_x(ui_TextArea3, -74);
//     lv_obj_set_y(ui_TextArea3, -94);
//     lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
//     lv_textarea_set_text(ui_TextArea3, "DATA");
//     lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");

//     ui_TextArea4 = lv_textarea_create(ui_DataScreen);
//     lv_obj_set_width(ui_TextArea4, 214);
//     lv_obj_set_height(ui_TextArea4, 166);
//     lv_obj_set_x(ui_TextArea4, 1);
//     lv_obj_set_y(ui_TextArea4, 16);
//     lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
//     lv_textarea_set_placeholder_text(ui_TextArea4, "Placeholder...");

//     uic_DataScreen = ui_DataScreen;

// }

// void ui_DataScreen_screen_destroy(void)
// {
//     if(ui_DataScreen) lv_obj_del(ui_DataScreen);

//     // NULL screen variables
//     uic_DataScreen = NULL;
//     ui_DataScreen = NULL;
//     ui_TextArea3 = NULL;
//     ui_TextArea4 = NULL;

// }
