// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: esp32_rc

#ifndef UI_DATASCREEN_H
#define UI_DATASCREEN_H

#ifdef __cplusplus
extern "C" {
#endif
#include "lvgl.h"
// SCREEN: ui_DataScreen
extern void ui_DataScreen_screen_init(void);
extern void ui_DataScreen_screen_destroy(void);
extern lv_obj_t * ui_DataScreen;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_TextArea4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_DataScreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

