// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: esp32_rc

#ifndef UI_MAINSCR_H
#define UI_MAINSCR_H

#ifdef __cplusplus
extern "C" {
#endif
#include "lvgl.h"
// SCREEN: ui_mainScr
extern void ui_mainScr_screen_init(void);
extern void ui_mainScr_screen_destroy(void);
extern lv_obj_t * ui_mainScr;
extern lv_obj_t * ui_rc1034;
// CUSTOM VARIABLES
extern lv_obj_t * uic_mainScr;
extern lv_obj_t * uic_rc1034;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

