// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: esp32_rc

#include "../ui.h"

lv_obj_t * uic_rc1034;
lv_obj_t * uic_mainScr;
lv_obj_t * ui_mainScr = NULL;
lv_obj_t * ui_rc1034 = NULL;
// event funtions

// build funtions

void ui_mainScr_screen_init(void)
{
    ui_mainScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rc1034 = lv_img_create(ui_mainScr);
    lv_img_set_src(ui_rc1034, &ui_img_1940168468);
    lv_obj_set_width(ui_rc1034, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_rc1034, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_rc1034, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rc1034, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rc1034, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_mainScr = ui_mainScr;
    uic_rc1034 = ui_rc1034;

}

void ui_mainScr_screen_destroy(void)
{
    if(ui_mainScr) lv_obj_del(ui_mainScr);

    // NULL screen variables
    uic_mainScr = NULL;
    ui_mainScr = NULL;
    uic_rc1034 = NULL;
    ui_rc1034 = NULL;

}
