// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: esp32_rc

#include "../ui.h"

lv_obj_t * uic_wifiINFOScreen;
lv_obj_t * ui_wifiINFOScreen = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
// event funtions

// build funtions

void ui_wifiINFOScreen_screen_init(void)
{
    ui_wifiINFOScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wifiINFOScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_wifiINFOScreen);
    lv_obj_set_width(ui_TextArea1, 129);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 73
    lv_obj_set_x(ui_TextArea1, 0);
    lv_obj_set_y(ui_TextArea1, 22);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "WIFI:1034esp32\n\nPSW:20041219");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_textarea_set_one_line(ui_TextArea1, true);

    ui_TextArea2 = lv_textarea_create(ui_wifiINFOScreen);
    lv_obj_set_width(ui_TextArea2, 216);
    lv_obj_set_height(ui_TextArea2, 54);
    lv_obj_set_x(ui_TextArea2, 5);
    lv_obj_set_y(ui_TextArea2, -59);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea2, "	    Connect ESP32wifi\nfor network configuration");
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");

    uic_wifiINFOScreen = ui_wifiINFOScreen;

}

void ui_wifiINFOScreen_screen_destroy(void)
{
    if(ui_wifiINFOScreen) lv_obj_del(ui_wifiINFOScreen);

    // NULL screen variables
    uic_wifiINFOScreen = NULL;
    ui_wifiINFOScreen = NULL;
    ui_TextArea1 = NULL;
    ui_TextArea2 = NULL;

}
