// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: esp32_rc

#ifndef UI_WIFIINFOSCREEN_H
#define UI_WIFIINFOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifiINFOScreen
extern void ui_wifiINFOScreen_screen_init(void);
extern void ui_wifiINFOScreen_screen_destroy(void);
extern lv_obj_t * ui_wifiINFOScreen;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_TextArea2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_wifiINFOScreen;
void setWifiInfoText(const char* info);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

